<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6FGI6U4\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6FGI6U4/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6FGI6U4.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6FGI6U4\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6FGI6U4\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6FGI6U4',
    'container.build_id' => '09b5fea2',
    'container.build_time' => 1615910120,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6FGI6U4');
