<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3cCu2fx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3cCu2fx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3cCu2fx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3cCu2fx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container3cCu2fx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '3cCu2fx',
    'container.build_id' => '4682d083',
    'container.build_time' => 1616059110,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3cCu2fx');
